language: cpp


dist: xenial
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-6
             - cmake
      env: COMPILER=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
             - cmake
      env: COMPILER=g++-7
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-8
             - cmake
      env: COMPILER=g++-8
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-7
             - ubuntu-toolchain-r-test
          packages:
             - clang++-7
             - libc++-7-dev
             - libc++abi-7-dev
             - cmake
      env: COMPILER=clang++-7 STDLIB="-s compiler.libcxx=libc++"

before_install:
  - pip install --user conan

install:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER"; export CXXFLAGS="-stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script: mkdir build && cd build && conan install .. $STDLIB && cmake -DCMAKE_CXX_STANDARD=17 .. && make && ./tests/tests
