language: cpp


dist: xenial
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-6
             - cmake
      env: COMPILER=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
             - cmake
      env: COMPILER=g++-7
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-8
             - cmake
      env: COMPILER=g++-8
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-6.0
             - ubuntu-toolchain-r-test
          packages:
             - clang++-6.0
             - libc++-dev
             - cmake
    env: COMPILER=clang++-6.0


before_install:
  - pip install --user conan

install:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script: mkdir build && cd build && conan install .. && cmake -DCMAKE_CXX_STANDARD=17 .. && make && ./tests/tests
