language: cpp


dist: xenial
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-6
             - cmake
      env: COMPILER=g++-6 C_COMPILER=gcc-6
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
             - cmake
      env: COMPILER=g++-7 C_COMPILER=gcc-7
    - compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-8
             - cmake
      env: COMPILER=g++-8 C_COMPILER=gcc-8
    - compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-7
             - ubuntu-toolchain-r-test
          packages:
             - clang++-7
             - libc++-7-dev
             - libc++abi-7-dev
             - clang-tools-7
             - cmake
      env: COMPILER=clang++-7 C_COMPILER=clang-7 STDLIB="-s compiler.libcxx=libc++" SCAN_BUILD="scan-build-7 --status-bugs -v"

before_install:
  - pip install --user conan

install:
    - if [ "$CXX" = "clang++" ]; then export CCC_CXX="$COMPILER"; export CCC_CC="$C_COMPILER"; export CXXFLAGS="-stdlib=libc++"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; export CC="$C_COMPILER"; fi

script: mkdir build && cd build && conan install .. $STDLIB && $SCAN_BUILD cmake -DCMAKE_CXX_STANDARD=17 .. && $SCAN_BUILD make && ./tests/tests
