language: cpp


dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.conan
    - $HOME/.cache/pip

stages:
  - clang-format-check
  - build

jobs:
  include:
    - stage: clang-format-check
      addons:
        apt:
          packages:
              - clang-format-6.0
      before_script: curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o utils/clang-format-diff.py
      script: ./utils/check_code_format.sh
      install: skip

    - stage: build
      compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-6
             - cmake
             - qtbase5-dev
             - libqt5charts5-dev
      env: COMPILER=g++-6 C_COMPILER=gcc-6
    - stage: build
      compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-7
             - cmake
             - qtbase5-dev
             - libqt5charts5-dev
      env: COMPILER=g++-7 C_COMPILER=gcc-7
    - stage: build
      compiler: gcc
      addons:
        apt:
          sources:
             - ubuntu-toolchain-r-test
          packages:
             - g++-8
             - cmake
             - qtbase5-dev
             - libqt5charts5-dev
      env: COMPILER=g++-8 C_COMPILER=gcc-8
    - stage: build
      compiler: clang
      addons:
        apt:
          sources:
             - llvm-toolchain-xenial-7
             - ubuntu-toolchain-r-test
          packages:
             - libstdc++-7-dev
             - clang-7
             - libc++1-7
             - libc++abi1-7
             - libc++-7-dev
             - libc++abi-7-dev
             - clang-tidy-7
             - cmake
             - qtbase5-dev
             - libqt5charts5-dev
      env: COMPILER=clang++-7 C_COMPILER=clang-7 CLANG_TIDY="-DCMAKE_CXX_CLANG_TIDY='clang-tidy-7;-warnings-as-errors;'"

install:
  - pip install --user conan

before_script:
    - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER"; export CC="$C_COMPILER"; fi
    - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; export CC="$C_COMPILER"; fi
    - bash -c "conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan; exit 0"

script: mkdir build && cd build && conan install -s compiler.libcxx=libstdc++11 --build missing .. $STDLIB && cmake $CLANG_TIDY -DCMAKE_CXX_STANDARD=17 .. && make -j2 && ./tests/tests
